site_name: JMP® Índice de scripts
theme: 
  name: readthedocs
  highlightjs: true
  locale: es
  hljs_languages:
    - python
  logo: img/JMPScriptingIndexLogo.svg
  collapse_navigation: false
  navigation_depth: 6
  include_homepage_in_sidebar: false
site_url: https://jsl.jmp.com/es
site_description: The JMP® Scripting Index provides a brief description and the syntax for JSL functions, objects, python integration, and display boxes for the JMP® Software.
copyright: © 2025 JMP Statistical Discovery LLC. Todos los derechos reservados.
use_directory_urls: false
extra_css:
  - css/jmpstyle.css
extra_javascript:
  - js/syntaxhighlighting.js
  - js/popper.min.js
  - js/tippy.js
  - js/extra.js
  - js/clipboard.js
plugins:
  - search:
      prebuild_index: true
  


