site_name: JMP スクリプトの索引
theme: 
  name: readthedocs
  custom_dir: custom_theme
  highlightjs: false
  locale: ja
  logo: img/JMPScriptingIndexLogo.svg
  collapse_navigation: false
  navigation_depth: 6
  include_homepage_in_sidebar: false
site_url: https://jsl.jmp.com/ja
site_description: The JMP Scripting Index provides a brief description and the syntax for JSL functions, objects, python integration, and display boxes for the JMP® Software.
copyright: © 2025 JMP Statistical Discovery LLC. All Rights Reserved.
use_directory_urls: false
extra_css:
  - css/jmpstyle.css
  - css/prism.css
extra_javascript:
  - js/prism.min.js
  - js/prism-custom.js
  - js/popper.min.js
  - js/tippy.js
  - js/extra.js
  - js/clipboard.js
plugins:
  - search:
      # prebuild_index: true
      indexing: sections
  


